name: Update Users

# Trigger manually via Actions → Run workflow
on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username to add'
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add username
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          USERNAME="${{ github.event.inputs.username }}"
          echo "Adding user: $USERNAME"
          # Make sure users.json exists in repo root
          jq ". + [\"$USERNAME\"]" users.json > tmp.json
          mv tmp.json users.json
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add users.json
          git commit -m "Add user $USERNAME"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
